<?php

namespace Database\Seeders;

use DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class InsuranceAgentSeeder extends Seeder
{

    public function run(): void
    {
        $data = [
            ['STATE FARM INSURANCE', 'LYNN FISHER', '201 S MAIN ST', 'ANDREWS', 'TX', '79714'],
            ['FARMERS INSURANCE', 'PAMELA ESCOBAR', '500 N MAIN ST', 'ANDREWS', 'TX', '79714'],
            ['STATE FARM INSURANCE', 'SUSIE BRAY', '214 TAHOKA RD', 'BROWNFIELD', 'TX', '79316'],
            ['FARMERS INSURANCE', 'JUDITH BESLER', '301 W BROADWAY ST', 'BROWNFIELD', 'TX', '79316'],
            ['BROWNFIELD INSURANCE AGENCY', 'LINDA ADKINS', '412 W MAIN', 'BROWNFIELD', 'TX', '79316'],
            ['ALLSTATE', 'LANDRY ODOM', '3721 S. STONEBRIDGE DR. - SUITE 204', 'MCKINNEY', 'TX', '75070'],
            ['THE NICHOLSON AGENCY', 'AMY NICHOLSON PAIVA', 'PO BOX 809', 'BROWNFIELD', 'TX', '79316'],
            ['STATE FARM INSURANCE', 'RUSSEL DIAL', 'PO BOX 1699', 'DENVER CITY', 'TX', '79323'],
            ['STATE FARM INSURANCE', 'NICK LONG', '201 W CALIFORNIA', 'FLOYDADA', 'TX', '79235'],
            ['STATE FARM INSURANCE', 'PAULA WADE', '101 MAIN ST', 'LAMESA', 'TX', '79331'],
            ['STATE FARM INSURANCE', 'JEANIE COOR', '101 Main Ave,', 'LAMESA', 'TX', '79331'],
            ['TEXAS FARM BUREAU', 'SHARALYN FERGUSON', 'PO BOX 1123', 'LAMESA', 'TX', '79331'],
            ['TEXAS FARM BUREAU', 'JIM SHOOK', 'PO BOX 1123', 'LAMESA', 'TX', '79331'],
            ['TEXAS FARM BUREAU', 'DENISE BARRON', 'PO BOX 1123', 'LAMESA', 'TX', '79331'],
            ['TEXAS FARM BUREAU', 'ALAN DAVIDSON', 'PO BOX 1123', 'LAMESA', 'TX', '79331'],
            ['HENRY NORRIS AGENCY', 'CHRIS NORRIS', 'PO DRAWER 1128', 'LAMESA', 'TX', '79331'],
            ['HENRY NORRIS AGENCY', 'ANESSA RENFRO', 'PO DRAWER 1128', 'LAMESA', 'TX', '79331'],
            ['MACHA INSURANCE', 'DEE MACHA', '813 8TH ST', 'LEVELLAND', 'TX', '79336'],
            ['STATE FARM INSURANCE', 'BILL ASHLEY', '820 AUSTIN ST', 'LEVELLAND', 'TX', '79336'],
            ['TEXAS FARM BUREAU', 'TREY THOMPSON', '1718 AVE H', 'LEVELLAND', 'TX', '79336'],
            ['STATE FARM INSURANCE', 'PETER GRIFFITH', '409 FRANKFORD', 'LUBBOCK', 'TX', '79416'],
            ['STATE FARM INSURANCE', 'JASON GRISHAM', '1102 SLIDE RD', 'LUBBOCK', 'TX', '79416'],
            ['FARMERS INSURANCE', 'KORY JOHNSON', '13041 QUAKER', 'LUBBOCK', 'TX', '79423'],
            ['STATE FARM INSURANCE', 'RODDY SIMMONS', '2123 34TH ST', 'LUBBOCK', 'TX', '79411'],
            ['STATE FARM INSURANCE', 'HAROLD BRADLEY', '2710 82ND ST, SUITE B', 'LUBBOCK', 'TX', '79423'],
            ['STATE FARM INSURANCE', 'HERSHAL SPEARS', '2710 82ND ST', 'LUBBOCK', 'TX', '79423'],
            ['FARMERS INSURANCE', 'CARLTON FREEMAN', '2738 82ND ST', 'LUBBOCK', 'TX', '79423'],
            ['STATE FARM INSURANCE', 'LYNN ALEXANDER', '3302 64TH ST', 'LUBBOCK', 'TX', '79413'],
            ['FARMERS INSURANCE', 'GARY HATCHETT', '3323 82ND ST', 'LUBBOCK', 'TX', '79423'],
            ['ARTHUR GALLAGHER RSIK MANAGEMNT', 'ARTHUR GALLAGHER', '2727 81ST', 'LUBBOCK', 'TX', '79423'],
            ['STATE FARM INSURANCE', 'ELROY CARSON', '3602 SLIDE RD, SUITE B7', 'LUBBOCK', 'TX', '79414'],
            ['FARMERS INSURANCE', 'STAN CRIBBS', '4101 84TH ST UNIT A', 'LUBBOCK', 'TX', '79423'],
            ['FARMERS INSURANCE', 'JOEY COOPER', '4101 84TH ST, SUITE A', 'LUBBOCK', 'TX', '79423'],
            ['FARMERS INSURANCE', 'BRENT HATCHETT', '4202 98TH ST, SUITE 101', 'LUBBOCK', 'TX', '79423'],
            ['FARMERS INSURANCE', 'NANNETTE ADKINS', '4407 71ST ST', 'LUBBOCK', 'TX', '79424'],
            ['FARMERS INSURANCE', 'ANTHONY BEVERS', '5124 82ND ST', 'LUBBOCK', 'TX', '79424'],
            ['FARMERS INSURANCE', 'CHRIS MADRIS', '5124 82ND ST', 'LUBBOCK', 'TX', '79424'],
            ['FARMERS INSURANCE', 'BILL HATCHETT', '5124 82ND ST', 'LUBBOCK', 'TX', '79424'],
            ['STATE FARM INSURANCE', 'DANNY LEAKE', '3913 114TH ST SUITE 20', 'LUBBOCK', 'TX', '79424'],
            ['FARMERS INSURANCE', 'DEBBIE DRURY', '13041 QUAKER', 'LUBBOCK', 'TX', '79423'],
            ['STATE FARM INSURANCE', 'DICK PHILLIPS', '5740 82ND ST', 'LUBBOCK', 'TX', '79424'],
            ['FARMERS INSURANCE', 'MICHAEL BERG', '5811 64TH ST UNIT A', 'LUBBOCK', 'TX', '79424'],
            ['STATE FARM INSURANCE', 'MIKE FOX', '5501 126TH ST, SUITE 121', 'LUBBOCK', 'TX', '79424'],
            ['INSUREALL, INC.', 'JOEL CLARY', '4412 74TH ST SUITE D-101', 'LUBBOCK', 'TX', '79424'],
            ['FARMERS INSURANCE', 'MISTY MULLINS', '13041 QUAKER', 'LUBBOCK', 'TX', '79423'],
            ['FARMERS INSURANCE', 'TOMMY POTTS', '13041 QUAKER', 'LUBBOCK', 'TX', '79423'],
            ['STATE FARM INSURANCE', 'KEN MARSHALL', '7805 SLIDE RD', 'LUBBOCK', 'TX', '79424'],
            ['BEDNAREZ & ASSOCIATES, LLC', 'DARREL BEDNARZ', '8008 SLIDE RD, SUITE 10', 'LUBBOCK', 'TX', '79424'],
            ['LONESTAR INSURANCE GROUP', 'TIM MONEYMAKER', '11006 INDIANA AVE #300', 'LUBBOCK', 'TX', '79423'],
            ['FARMERS INSURANCE', 'RHETT RICHARDSON', '13413 CR 1800, SUITE D', 'LUBBOCK', 'TX', '79424'],
            ['STATE FARM INSURANCE', 'REBECCA EGERT', '9810 INDIANA AVE, SUITE 120', 'LUBBOCK', 'TX', '79423'],
            ['STATE FARM INSURANCE', 'KAITLIN FERGESON', '1707 30TH ST, SUITE C', 'SNYDER', 'TX', '79549'],
            ['STATE FARM INSURANCE', 'JASON SALES', '9117 NEWALKE AVE SUITE 300', 'LUBBOCK', 'TX', '79424'],
            ['FARMERS INSURANCE', 'JULES MINNE', '202 82ND ST SUITE 102', 'LUBBOCK', 'TX', '79423'],
            ['FARMERS INSURANCE', 'ALEXIS HADEN', '10309 INDIANA AVE, SUITE B', 'LUBBOCK', 'TX', '79423'],
            ['WILLCOXON INSURANCE AGENCY', 'ERIK WILLCOXON', '4714 LOOP 289', 'LUBBOCK', 'TX', '79424'],
            ['TEXAS FARM BUREAU', 'BILLY STEPHENS', '10615 QUAKER AVE', 'LUBBOCK', 'TX', '79424'],
            ['TEXAS FARM BUREAU', 'AMY RIGGAN', '10615 QUAKER AVE', 'LUBBOCK', 'TX', '79423'],
            ['STATE FARM INSURANCE', 'HAROLD BRADLEY', '2710 B 82ND ST', 'LUBBOCK', 'TX', '79423'],
            ['TEXAS FARM BUREAU', 'GABE MORENO', 'PO BOX 908', 'TAHOKA', 'TX', '79373'],
            ['FARMERS INSURANCE', 'BRYAN BOYD', '6905 82ND ST STE 400', 'LUBBOCK', 'TX', '79424'],
            ['ALLSTATE INSURANCE', 'RUSSELL DONOWAY', '2321 50TH ST STE C', 'LUBBOCK', 'TX', '79412'],
            ['LIBERTY MUTUAL INSURANCE', 'ROSA POMPA', '4010 82ND ST # 255', 'LUBBOCK', 'TX', '79423'],
            ['SIG INSURANCE', 'JEREMY DANSBY', '5147 69TH ST STE A', 'LUBBOCK', 'TX', '79424'],
            ['FARMERS INSURANCE', 'JOHN McGAVOCK', '2219 W 5TH ST', 'PLAINVIEW', 'TX', '79072'],
            ['TEXAS FARM BUREAU', 'GABE MORENO', '117 E MAIN ST', 'POST', 'TX', '79356'],
            ['ALLSTATE INSURANCE', 'DOUG TOWNSEND', '6845 82ND ST SUITE 103', 'LUBBOCK', 'TX', '79424'],
            ['TRAVELERS INSURANCE', 'RHOADS BROTHERS LLC', '306 ARNETT', 'ROPESVILLE', 'TX', '79358'],
            ['FARMERS INSURANCE', 'DON DAGLEY', '100 SW 7TH ST', 'SEMINOLE', 'TX', '79360'],
            ['STATE FARM INSURANCE', 'GUY CHANEY', '400 S MAIN', 'SEMINOLE', 'TX', '79360'],
            ['STATE FARM INSURANCE', 'LANDON SIMS', '400 S MAIN', 'SEMINOLE', 'TX', '79360'],
            ['GEORGE KEELING INSURANCE', 'IRIS KEELING', '507 AVE G', 'LEVELLAND', 'TX', '79336'],
            ['TEXAS FARM BUREAU', 'TERRY KENT', 'PO BOX 128', 'SEMINOLE', 'TX', '79360'],
            ['STATE FARM INSURANCE', 'KEVIN WATSON', '3524 34TH ST', 'LUBBOCK', 'TX', '79410'],
            ['FARM BUREAU INSURANCE', 'KATIE SHAFER', '5605 AVE Q SOUH DRIVE', 'LUBBOCK', 'TX', '79423'],
            ['STATE FARM INSURANCE', 'KO DAVIS', '105 N 10TH ST', 'SLATON', 'TX', '79364'],
            ['FARMERS INSURANCE', 'GREG HATCHETT', '5124 82ND ST', 'LUBBOCK', 'TX', '79424'],
            ['FARMERS INSURANCE', 'JOHN McGAVOCK', '2219 W 5TH ST', 'PLAINVIEW', 'TX', '79072'],
            ['FARMERS INSURANCE', 'LANCE EDWARDS', '110 HOUSTON ST', 'LEVELLAND', 'TX', '79336'],
            ['FARMERS INSURANCE', 'JOEY COOPER', '4101 84TH ST, UNIT A', 'LUBBOCK', 'TX', '79423'],
            ['TRAVELERS INSURANCE', 'STRINGER INSURANCE AGENCY', '2208 MAIN ST', 'TAHOKA', 'TX', '79373'],
            ['SIG INSURANCE', 'JOEL DANSBY', '5147A 69TH ST', 'LUBBOCK', 'TX', '79424'],
            ['HORACE MANN INSURANCE', 'BOBBY HERNDON', '8212 ITHACA AVE STE H', 'LUBBOCK', 'TX', '79423'],
            ['TEXAS FARM BUREAU INS. CO', 'RENE LONGUNA', '521 W MAIN ST', 'BROWNFIELD', 'TX', '79316'],
        ];

        foreach ($data as $item) {
            DB::table('insurance_agents')->insert([
                'agency_name' => $item[0],
                'agent_name' => $item[1],
                'address_line' => $item[2],
                'city' => $item[3],
                'state' => $item[4],
                'zip' => $item[5],
                'company_id' => 1,
            ]);
        }
    }
}
